import Link from 'next/link'
import './globals.css'
import type { Metadata } from 'next'

type TopicT = {
  id: number;
  title: string;
  body: string;
}

// export const metadata: Metadata = {
//   title: 'WEB tutorial',
//   description: 'Generated by je',
// }

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const resp = await fetch('http://localhost:9999/topics')
  const topics = await resp.json();
  return (
    <html>
      <body>
        <h1><Link href="/">WEB</Link></h1>
        <ol>
          {topics.map((topic: TopicT) => {
            return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
          })}
        </ol>
        {children}
        <ul>
          <li><Link href="/create">create</Link></li>
          <li><Link href="/update/id">update</Link></li>
          <li><button>delete</button></li>
        </ul>
      </body>
    </html>
  )
}
